export class Customer{
    cust_id:string;
    cust_code:string;
    cust_name:string;
    cust_gender:string;
    cust_datebirth:string;
    cust_nation:string;
    cust_phone:string;
    cust_email:string;
    cust_type:string;
    cust_regime:string;
    cust_smoke:string;
    cust_drink:string;
    cust_room:string;
    cust_gain:string;
    cust_deposit:string;
    cust_status:string;
    cust_active:string;
    cust_active_room:string;
    cust_date_creat:string;
    user_name:string;
 }